version: '3.8'

services:
  mysqldb:
    image: "mysql:8.2"
    restart: always
    ports:
      - 3306:3306
    networks:
      - springmysql-net
    environment:
      MYSQL_DATABASE: budgetin
      MYSQL_USER: budgetin
      MYSQL_PASSWORD: budgetin
      MYSQL_ROOT_PASSWORD: budgetin

  api_service:
    build: .
    depends_on:
      - mysqldb
    restart: always
    ports:
      - 8080:8080
    networks:
      - springmysql-net
    volumes:
      - .m2:/root/.m2

networks:
  springmysql-net:

