spring:
  devtools:
    livereload:
      enabled: true
    add-properties: false
    restart:
      enabled: 'true'
      poll-interval: 2s
      quiet-period: 1s
      additional-paths:
      - src/main/java/

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    type: com.zaxxer.hikari.HikariDataSource
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50

  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[show_sql]': ${JPA_SHOW_SQL}
        '[format_sql]': ${JPA_SHOW_SQL}

logging:
  level:
    web: WARN
    root: INFO
    org:
      springframework:
        web: DEBUG
      hibernate: WARN

server:
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true
    path: /error
