name: 🧪 CI and 🚀 CD

on:
  push:
    branches: ["main", "dev"]
    # paths:
    #   - 'src/**'

jobs:
  unit_test_for_old_java_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        distribution: ['zulu', 'temurin', 'microsoft']
        java: ['17', '21']
    name: Unit Test with JDK ${{ matrix.Java }} ${{ matrix.distribution }}
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test

  code_coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Code Coverage Check with JDK 21
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'KAnggara75'
          git config --global user.email '24321218@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jacoco-report
        path: target/site/jacoco/
        overwrite: true

  versioning:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11.0
        with:
          versionSpec: "5.10.x"
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11.0
      - name: Create version.txt with NuGetVersionV2
        run: echo ${{ steps.gitversion.outputs.NuGetVersionV2  }} > version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v4.3.1
        with:
          name: gitversion
          path: version.txt
          overwrite: true

  build_package:
    runs-on: ubuntu-latest
    needs: [versioning, unit_test_for_old_java_version]
    permissions:
      contents: write
      pull-requests: write
    name: Build app with Maven and JDK 21
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: maven
    - name: Download Version
      uses: actions/download-artifact@v4.1.3
      with:
        name: gitversion
    - name: Build package with Maven
      run: |
        ls -la
        VER=`cat version.txt`
        sed -i 's/\<version\>9.9.9.*/\<version\>$VER\<\/version\>/' pom.xml
    - name: Build package with Maven
      run: mvn clean package -Dmaven.test.skip=true
    - name: Upload package artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: BudgetIn
        path: target/BudgetIn.jar
        overwrite: true

  release_note:
    name: Create Release Note
    needs: code_coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Upload CHANGELOG.md
        uses: actions/upload-artifact@v4.3.1
        with:
          name: changelog
          path: CHANGELOG.md
          overwrite: true

  release:
    name: Create Release
    needs: [release_note, build_package]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4.1.3
      - name: Display structure of downloaded files
        run: |
          ls -R
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./gitversion/version.txt
      - name: Create Release
        uses: ncipollo/release-action@v1.14.0
        with:
          artifacts: "./BudgetIn/BudgetIn.jar"
          tag: ${{ steps.version.outputs.content }}
          bodyFile: "./changelog/CHANGELOG.md"

  deploy:
    name: Deploy new Package
    needs: build_package
    runs-on: ubuntu-latest
    steps:
      - name: Download all Artifact
        uses: actions/download-artifact@v4.1.3
        with:
          name: BudgetIn
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "./BudgetIn.jar"
          target: /home/idscript/app

  # TODO: Restart service
  job_3:
    name: 3 Display results
    needs: [deploy, release]
    runs-on: ubuntu-latest
    steps:
      - name: Download all Artifact
        uses: actions/download-artifact@v4.1.3
        with:
          name: gitversion
      - name: Print the final result
        run: |
          value=`cat version.txt`
          echo The result is $value

  # unit_test_latest_java_version:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Test Restart
  #     uses: appleboy/ssh-action@v1.0.3
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USER }}
  #       key: ${{ secrets.SSH_KEY }}
  #       port: ${{ secrets.SSH_PORT }}
  #       passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #       script_stop: true
  #       script: |
  #         cd ~/work/SpringBoot
  #         git restore .
  #         git pull
  #         ./restart.sh
  #         sudo systemctl restart budgetin
