name: 🧪 CI and 🚀 CD

on:
  push:
    branches: [ "main", "qa", "dev" ]
  pull_request:
    branches: [ "main", "qa", "dev" ]
    paths:
      - 'src/**'

jobs:
  unit_test_for_old_java_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        java: [ '8', '11', '17', '21' ]
    name: Unit Test with Java ${{ matrix.Java }}
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test

  unit_test_latest_java_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Unit Test with Java 21
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test

  job_3:
    name: Display results
    needs: [unit_test_latest_java_version, unit_test_for_old_java_version]
    runs-on: macOS-latest
    steps:
      - name: Download math result for job 2
        uses: actions/download-artifact@v3
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat math-homework.txt`
          echo The result is $value

  # unit_test_latest_java_version:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Test Restart
  #     uses: appleboy/ssh-action@v1.0.3
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USER }}
  #       key: ${{ secrets.SSH_KEY }}
  #       port: ${{ secrets.SSH_PORT }}
  #       passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #       script_stop: true
  #       script: |
  #         cd ~/work/SpringBoot
  #         git restore .
  #         git pull
  #         ./restart.sh
  #         sudo systemctl restart budgetin

  # unit_test_latest_java_version:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Test Restart
  #     uses: appleboy/ssh-action@v1.0.3
  #     with:
  #       host: ${{ secrets.SSH_HOST }}
  #       username: ${{ secrets.SSH_USER }}
  #       key: ${{ secrets.SSH_KEY }}
  #       port: ${{ secrets.SSH_PORT }}
  #       passphrase: ${{ secrets.SSH_PASSPHRASE }}
  #       script_stop: true
  #       script: |
  #         cd ~/work/SpringBoot
  #         git restore .
  #         git pull
  #         ./restart.sh
  #         sudo systemctl restart budgetin
