name: 🧪 CI and 🚀 CD

on:
  push:
    branches: [ "main", "qa", "dev" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main", "qa", "dev" ]
    paths:
      - 'src/**'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        java: [ '17', '21' ]
    name: Unit Test with Java ${{ matrix.Java }}
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'microsoft'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test

  unit_test2:
    runs-on: ubuntu-latest
    steps:
    - name: Test Restart
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script_stop: true
        script: |
          cd ~/work/SpringBoot
          git restore .
          git pull
          ./restart.sh
          sudo systemctl restart budgetin
