name: 🧪 Java CI-Maven

on:
  push:
    branches: [ "main", "qa" ]
  pull_request:
    branches: [ "main", "qa", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ (contains(github.event.head_commit.message, '#war') || contains(github.event.head_commit.message, '#build')) && github.ref == 'refs/heads/main'}}
    env:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: root
      MYSQL_DB_NAME: budgetin
      MYSQL_DB_HOST: localhost:3306
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DB_NAME;" -u$MYSQL_DB_USERNAME -p$MYSQL_DB_PASSWORD
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven Dependency Tree Dependency Submission
      uses: advanced-security/maven-dependency-submission-action@v3.0.3
            
