name: Java CI with Maven

on:
  push:
    branches: [ "main", "qa" ]
  pull_request:
    branches: [ "main", "qa", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Set db Connection
      run: |
        export MYSQL_DB_USERNAME=${{ secrets.MYSQL_DB_USERNAME }}
        export MYSQL_DB_PASSWORD=${{ secrets.MYSQL_DB_PASSWORD }}
        export MYSQL_DB_HOST=${{ secrets.MYSQL_DB_HOST }}
        export MYSQL_DB_NAME=${{ secrets.MYSQL_DB_NAME }}
        echo $MYSQL_DB_NAME
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
