name: 🚀 Test SSH Access

on:
  push:
    branches: [ "main"]
    paths:
      - 'src/**'

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Test Restart
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script_stop: true
        script: |
          cd ~/work/SpringBoot
          git restore .
          git pull
          ./restart.sh
          sudo systemctl restart budgetin
