name: 🔬 Maven Unit Test

on:
  push:
    branches: [ "main", "qa", "dev" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main", "qa", "dev" ]
    paths:
      - 'src/**'

jobs:
  unit_test_for_old_java_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      matrix:
        distribution: ['zulu', 'temurin', 'microsoft']
        java: ['17', '21']
    name: Unit Test with JDK ${{ matrix.Java }} ${{ matrix.distribution }}
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distribution }}
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test

  code_coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Code Coverage Check with JDK 21
    env:
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: budgetin
      DB_HOST: localhost
      DB_PORT: 3306
      JPA_SHOW_SQL: true
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: maven
    - name: Start MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e "CREATE DATABASE IF NOT EXISTS $DB_NAME;" -u$DB_USERNAME -p$DB_PASSWORD
    - name: Build with Maven
      run: mvn clean test
    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
    - name: Commit the badge (if it changed)
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --global user.name 'KAnggara75'
          git config --global user.email '24321218@users.noreply.github.com'
          git add -A
          git commit -m "Autogenerated JaCoCo coverage badge"
          git push
        fi
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jacoco-report
        path: target/site/jacoco/
        overwrite: true
